name: Docker Image CI
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx      
        uses: crazy-max/ghaction-docker-buildx@v1      
        with:        
          version: latest

      - name: Login to DockerHub
        if: success()
        run: |
          docker login --username tnioa --password ${{ vars.DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker image     
        if: success()
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t tnioa/nuvelu-ui:1.0.${{ github.run_number }} --output type=image,push=true .